- name: Echo
  hosts: "{{SELECT_HOST}}"
  tasks:

    - name: Print text
      debug:
        msg: "{{TEXT_TO_PRINT}}"
        - name: ansible create directory with mode setting example
          file:
            path: /tmp/devops_directory
            state: directory
            mode: "u=rw,g=wx,o=rwx"
